// 17vue/calculator/src/main/Calculator.vue
<template>
  <div class="calculator">
      <Display :value="displayValue"/>
      <Button label="AC" triple @onclick="clearMemory"/>
      <Button label="/" operation @onclick="setOperation"/>
      <Button label="7" @onclick="addDigit"/>
      <Button label="8" @onclick="addDigit"/>
      <Button label="9" @onclick="addDigit"/>
      <Button label="*" operation @onclick="setOperation"/>
      <Button label="4" @onclick="addDigit"/>
      <Button label="5" @onclick="addDigit"/>
      <Button label="6" @onclick="addDigit"/>
      <Button label="-" operation @onclick="setOperation"/>
      <Button label="1" @onclick="addDigit"/>
      <Button label="2" @onclick="addDigit"/>
      <Button label="3" @onclick="addDigit"/>
      <Button label="+" operation @onclick="setOperation"/>
      <Button label="0" double @onclick="addDigit"/>
      <Button label="." @onclick="addDigit"/>
      <Button label="=" operation @onclick="setOperation"/>

  </div>
</template>

<script>

import Display from "../components/Display"
import Button from "../components/Button"

export default {
    //data é onde fica as constantes que serão utilizadas no código
    data:function(){
        return{
            displayValue:"0",
            clearDisplay:false,
            operation: null,
            values: [0, 0],
            current: 0
        }
    },
    //após importar os componentes é necessário registrálos como abaixo:
    components:{Button, Display },
    methods:{
        clearMemory(){
            //função do VueJs abaixo estamos fazendo o objeto voltar ao seu estado original
            Object.assign(this.$data, this.$options.data())
        },

        setOperation(operation){
            //verifica se estamos no current 0 o que significa que ainda estamos digitando o primeiro valor
            if(this.current === 0 ){
                //lembrando que quando usamos o this na frente da constante estamos invocando a constante presente em data:function()
                this.operation = operation
                this.current = 1
                this.clearDisplay = true
            } else {
                //se a operação for '=' iremos armazenar um true para utilizar para limpar ou não o display
                const equals = operation === "="
                const currentOperation = this.operation

                try{
                    //eval realiza a execução de uma expressão javascript, abaixo estamos realizando o cálculo utilizando os valores e a operação
                    this.values[0] = eval(
                        `${this.values[0]} ${currentOperation} ${this.values[1]}`
                    )
                } catch(e){
                    //$emit é utilizado para emitir o erro que pode ser tratado por quem utilizar o componente calculator
                    this.$emit('onErro', e)
                }

                //ao realizar o cálculo retornamos values[1] = 0 para depois se for o caso realizar novos cálculos
                this.values[1] = 0

                //o valor exibido no display recebe o resultado da operação matematica entre os dois valores
                this.displayValue = this.values[0]
                //se a operação for '=' não terá outra operação, senão this.operation será = operation
                this.operation = equals ? null: operation
                this.current = equals ? 0 : 1
                this.clearDisplay = !equals//limpará o display se escolhermos outra operação matemática que não seja '='
            }
        },
        addDigit(n){
            //verifica se o valor do display já possue '.' se sim não digita outro
            if(n === "." && this.displayValue.includes(".")){
                return
            }

            //limpa o display se no display estiver '0' ou se clearDisplay estiver true
            const clearDisplay = this.displayValue === "0"
                || this.clearDisplay
            //currentValue recebe "vazio" se clearDisplay estiver true ou recebe o this.displayValue
            const currentValue = clearDisplay ? "" : this.displayValue
            const displayValue = currentValue + n // displayValue recebe o valor atual do display + novo valor

            this.displayValue = displayValue//atribui o valor atual do display ao this.displayValue que armazena em data:function()
            this.clearDisplay = false

            if(n != "."){
                //se n for diferente de '.' iremos armazenar o valor do display em this.values[i]
                const i = this.current
                const newValue = parseFloat(displayValue)
                this.values[i] = newValue
            }
        }
    }
}
</script>

<style>
.calculator{
    height: 320px;
    width: 235px;
    border-radius: 5px;
    overflow: hidden;

    display: grid;
    grid-template-columns: repeat(4, 25%);
    grid-template-rows: 1fr 48px 48px 48px 48px 48px;
}
</style>

// 16React/calculadora/src/main/Calculator.jsx
import React, {Component} from 'react'
import './Calculator.css'
import Button from '../components/button'
import Display from '../components/display'

//objeto criado para armazernar os estados inicias, como valor do display, valor atual, e outros
const initialState = {
    displayValue: '0',
    clearDisplay: false,
    operation: null,
    values: [0, 0],
    current: 0
}

export default class Calculator extends Component{

    state = {...initialState}//state recebe todos os atributos de initialState

    constructor(props){
        super(props)//necessário para iniciar os atributos

        //lembrando que usamos o código abaixo para forçar que o this.function aponte para o local correto
        this.clearMemory = this.clearMemory.bind(this)
        this.setOperation = this.setOperation.bind(this)
        this.addDigit = this.addDigit.bind(this)
    }

    clearMemory(){
        //ao executar clearMemory o state é setado para o estado original
        this.setState({...initialState})
    }

    setOperation(operation){
        console.log(operation)
    }

    addDigit(n){
        //se já existir um '.' no display ao clicar no . não será adicionado outro ponto
        if(n === '.' && this.state.displayValue.includes('.')){
            return
        }
        /**
         * clearDisplay recebe a solução do teste lógico que verifica se o
         * displayValue atual é '0' ou se clearDisplay está setado como true
         * sendo assim caso um dos testes seja true clear display será true
         */
        const clearDisplay = this.state.displayValue === '0'
            || this.state.clearDisplay

        //currentValue verifica se clearDisplay está true se sim current value recebe vazio ou recebe o valor que está no display
        const currentValue = clearDisplay ? '' : this.state.displayValue

        //displayValue recebe current value + o novo valor digitado
        const displayValue = currentValue + n

        //após isso é setado os valores de displayValue e de clearDisplay
        this.setState({displayValue, clearDisplay: false})

        if(n != '.'){
            const i = this.state.current

            //newValue recebe o parse de displayValue o que transforma String para Float
            const newValue = parseFloat(displayValue)

            //values recebe uma cópia dos values que estão em state
            const values = [...this.state.values]
            values[i] = newValue

            //após o processamento dos valores os mesmos são setados em state
            this.setState({values})
        }
    }
    render(){
        
        return (
            <div className="calculator">
                <Display value={this.state.displayValue}/>
                <Button label="AC" click={this.clearMemory} triple/>
                <Button label="/"click={this.setOperation} operation/>
                <Button label="7" click={this.addDigit}/>
                <Button label="8"click={this.addDigit}/>
                <Button label="9"click={this.addDigit}/>
                <Button label="*"click={this.setOperation} operation/>
                <Button label="4"click={this.addDigit}/>
                <Button label="5"click={this.addDigit}/>
                <Button label="6"click={this.addDigit}/>
                <Button label="-"click={this.setOperation} operation/>
                <Button label="1"click={this.addDigit}/>
                <Button label="2"click={this.addDigit}/>
                <Button label="3"click={this.addDigit}/>
                <Button label="+"click={this.setOperation} operation/>
                <Button label="0"click={this.addDigit} double/>
                <Button label="."click={this.addDigit}/>
                <Button label="="click={this.setOperation} operation/>

            </div>
            )
        
    }
}
